publish-logs:
  image: publish-logs
  ports:
    - "6060:5000"
  links:
    - db-server

retrieve-logs:
  image: retrieve-logs
  ports:
    - "6070:5000"
  links:
    - db-server

db-server:
  image: db-server
  ports:
    - "6071:6071"
    - "6061:6061"
