publish-logs:
  image: publish-logs
  ports:
    - "6060:6060"
  links:
    - db-server

retrieve-logs:
  image: retrieve-logs
  ports:
    - "6070:6070"
  links:
    - db-server

db-server:
  image: db-server
  env_file:
    - config.env
  ports:
    - "6071:6071"
    - "6061:6061"
